### ISSUE TITLE
Fongo and Morphia

### ISSUE THREAD

**Issue by Lugribossk** [foursquare/fongo#18]
I'm trying to use Fongo together with Morphia (https://github.com/jmkgreen/morphia), however I've run into two issues:

When calling Datastore#merge() it fails with the following exception.
com.github.jmkgreen.morphia.query.UpdateException: Not updated: { "serverUsed" : "0.0.0.0/0.0.0.0:27017" , "ok" : true , "n" : 1}
It seems to expect getLastError for the update to contain the text "updatedExisting".

When saving and then getting an object that has a DBRef to another object (via Morphia's @Reference), the DBRefBase will have a null _db field, which makes it throw an exception.

Both of these cases work if I connect to a real Mongo server rather than Fongo.

**Comment by hoffrocket** [comment]
I'll try to add this feature in.  Thanks for reporting.

**Comment by hoffrocket** [comment]
Ah, sorry, I missed that part of the issue. I'll try to reproduce and fix.

**Comment by hoffrocket** [comment]
I attempted to reproduce with a simple test (
https://github.com/foursquare/fongo/commit/8af0bbace98fbfc52017af60c8251bd978f64dee)
, but I guess something else is going on with morphia. Could you send me a
full stack trace?

**Comment by jasondemorrow** [comment]
I'm getting this too. Here's the relevant portion of the stack trace, but not sure it'll be helpful since it's after the fact.

java.lang.RuntimeException: no db
    at com.mongodb.DBRefBase.fetch(DBRefBase.java:49)
    at com.google.code.morphia.mapping.ReferenceMapper.resolveObject(ReferenceMapper.java:293)
    at com.google.code.morphia.mapping.ReferenceMapper.readSingle(ReferenceMapper.java:185)
    at com.google.code.morphia.mapping.ReferenceMapper.fromDBObject(ReferenceMapper.java:165)
    at com.google.code.morphia.mapping.Mapper.readMappedField(Mapper.java:602)
    at com.google.code.morphia.mapping.Mapper.fromDb(Mapper.java:584)
    at com.google.code.morphia.mapping.Mapper.fromDBObject(Mapper.java:294)
    at com.google.code.morphia.query.MorphiaIterator.convertItem(MorphiaIterator.java:71)
    at com.google.code.morphia.query.MorphiaIterator.processItem(MorphiaIterator.java:58)
    at com.google.code.morphia.query.MorphiaIterator.next(MorphiaIterator.java:53)
    at com.google.code.morphia.query.QueryImpl.asList(QueryImpl.java:290)

**Comment by twillouer** [comment]
Witch version of fongo do you use ?

**Comment by jasondemorrow** [comment]
Build from source

**Comment by jbyler** [comment]
I'm seeing this stack trace too, using Fongo 1.2.0, when morphia attempts to resolve a field that is marked @org.mongodb.morphia.annotations.Reference.

**Comment by twillouer** [comment]
Fongo has been moved here : https://github.com/fakemongo/fongo

Can you try with this :

``` xml
<dependency>
  <groupId>com.github.fakemongo</groupId>
  <artifactId>fongo</artifactId>
  <version>1.3.6</version>
  <scope>test</scope>
</dependency>
```

(take care, the "Fongo" object is now com.github.fakemongo.Fongo)

(v1.3.6 available soon)

**Comment by james-jory** [comment]
For posterity.... if anyone else is using an older/forked version of morphia and runs across this problem, a fix was made in morphia. 

https://github.com/mongodb/morphia/issues/507
