### ISSUE TITLE
FongoDBCollection.idsIn(DBObject) throws ClassCastException

### ISSUE THREAD

**Issue by grahamar** [foursquare/fongo#22]
Firstly, thank you so much for this framework, it's made my life so much easier!

When executing MongoTemplate.find(Query.query(Criteria.where("id").in(ids)), class) using Fongo I get the below exception as an Object[] is being cast to a List.

Offending Lines

``` java
     else if (idValue instanceof DBObject ){
          DBObject idDbObject = (DBObject)idValue;
          List inList = (List)idDbObject.get(ExpressionParser.IN);
```

Exception:

``` java
    java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to java.util.List
        at com.mongodb.FongoDBCollection.idsIn(FongoDBCollection.java:228)
        at com.mongodb.FongoDBCollection.__find(FongoDBCollection.java:349)
        at com.mongodb.DBCursor._check(DBCursor.java:368)
        at com.mongodb.DBCursor._hasNext(DBCursor.java:459)
        at com.mongodb.DBCursor.hasNext(DBCursor.java:484)
        at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1541)
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1347)
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1333)
        at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:505)
        at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:500)
        at com.im.sonic.data.spi.service.AbstractServiceImpl.findAll(AbstractServiceImpl.java:88)
        at com.im.sonic.data.spi.service.AuthorServiceImpleTest.testFindAll(AuthorServiceImpleTest.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
        at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
        at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

**Comment by grahamar** [comment]
Fixed and Pull Request Sent.
See Pull Request#23
